controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Category;
use app\models\Post;
use app\models\StaticPage;
use app\models\Tag;
use PHPUnit\Framework\Exception;
use webvimark\modules\UserManagement\models\forms\ChangeOwnPasswordForm;
use webvimark\modules\UserManagement\models\User;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\widgets\ActiveForm;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $latestPosts = new ActiveDataProvider([
            'query' => Post::find()->where(['is_published' => true])->orderBy('published_at desc'),
            'pagination' => [
                'pagesize' => 2,
            ],]);

        return $this->render('index', [
            'latestPosts' => $latestPosts
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionCategoryPage($categoryOrPageUrl)
    {
        /** @var StaticPage $page */
        if ($page = StaticPage::find()->where(['is_published' => true])
            ->andWhere(['url' => $categoryOrPageUrl])->one()
        ) {

            if ($page->is_form) {

                $model = new ContactForm();

                if (Yii::$app->request->isAjax AND $model->load(Yii::$app->request->post())) {
                    Yii::$app->response->format = Response::FORMAT_JSON;
                    return ActiveForm::validate($model);
                }

                if ($model->load(Yii::$app->request->post())) {
                    if ($model->contact(Yii::$app->params['adminEmail'])) {
                        Yii::$app->session->setFlash('contactFormSubmitted');
                        return $this->refresh();
                    } else {
                        throw new Exception(print_r($model->getErrors(), true));
                    }
                }

            }

            return $this->render('page', [
                'model' => $page
            ]);

        } elseif ($category = Category::find()
            ->where(['is_published' => true])
            ->andWhere(['url' => $categoryOrPageUrl])
            ->one()
        ) {
            /** @var Category $category */
            $categoryPosts = new ActiveDataProvider([
                'query' => $category->getPosts()->orderBy('published_at desc'),
                'pagination' => [
                    'pagesize' => 2,
                ],
            ]);

            return $this->render('category', [
                'categoryPosts' => $categoryPosts,
                'categoryName' => $category->name
            ]);
        }

        throw new NotFoundHttpException();
    }

    public function actionPost($categoryUrl, $postUrl)
    {
        if ($post = Post::find()
            ->where([Post::tableName() . '.url' => $postUrl])
            ->andWhere([Post::tableName() . '.is_published' => true])
            ->joinWith('category')
            ->andWhere([Category::tableName() . '.url' => $categoryUrl])->one()
        ) {
            return $this->render('post', [
                'model' => $post
            ]);
        }

        throw new NotFoundHttpException();
    }

    public function actionTag($tagUrl)
    {
        /** @var Tag $tag */
        if ($tag = Tag::find()->where(['url' => $tagUrl])->andWhere(['is_published' => true])->one()) {

            $tagPosts = new ActiveDataProvider([
                'query' => $tag->getPosts()->orderBy('published_at desc'),
                'pagination' => [
                    'pagesize' => 2,
                ],
            ]);

            return $this->render('tag', [
                'tagPosts' => $tagPosts,
                'tagName' => $tag->name
            ]);
        }

        throw new NotFoundHttpException();
    }

    public function actionProfile()
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $user = User::getCurrentUser();

        if ($user->status != User::STATUS_ACTIVE) {
            throw new ForbiddenHttpException();
        }

        $model = new ChangeOwnPasswordForm(['user' => $user]);


        if (Yii::$app->request->isAjax AND $model->load(Yii::$app->request->post())) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }

        if ($model->load(Yii::$app->request->post()) AND $model->changePassword()) {
            Yii::$app->session->setFlash('success', 'Password has been changed');
            return $this->refresh();
        }

        return $this->renderIsAjax('profile', compact('model'));

    }

    protected function renderIsAjax($view, $params = [])
    {
        if (Yii::$app->request->isAjax) {
            return $this->renderAjax($view, $params);
        } else {
            return $this->render($view, $params);
        }
    }
}

views/site/_short_post_view.php
<?php

/** @var \app\models\Post $model */
use app\models\Post;
use yii\helpers\Html;
use yii\helpers\Url;

?>

<div class="col-sm-12 col-md-12">
    <div class="single-blog single-column">
        <div class="post-thumb">
            <a href="blogdetails.html">
                <!--                <img src="images/blog/7.jpg" class="img-responsive" alt="">-->
            </a>
            <div class="post-overlay">
                <span class="uppercase"><a href="#">14 <br><small>Feb</small></a></span>
            </div>
        </div>
        <div class="post-content overflow">
            <h2 class="post-title bold"><?= Html::a($model->name, [
                    'site/post',
                    'categoryUrl' => $model->category->url,
                    'postUrl' => $model->url
                ]) ?></h2>
            <h3 class="post-author">Published <?= date('l jS \of F Y h:i:s A', $model->published_at) ?>
            </h3>
            <p><?= $model->short_content ?> [...]</p>
            <?= Html::a('View More', ['site/post', 'categoryUrl' => $model->category->url, 'postUrl' => $model->url],
                ['class' => 'read-more']) ?>
            <div class="post-bottom overflow">
                <ul class="nav navbar-nav post-nav">
                    <?php foreach ($model->publishedTags as $tag) : ?>
                        <li><?= Html::a('<i class="fa fa-tag"></i>' . $tag->name,
                                ['site/tag', 'tagUrl' => $tag->url]) ?></li>
                    <?php endforeach ?>
                    <li><?= Html::a('<i class="fa fa-list-ul"></i>' . $model->category->name,
                            ['site/category-page', 'categoryOrPageUrl' => $model->category->url]) ?></li>
                    <li><a href="<?= Url::to([Post::getPostFullUrlByEntity($model->id)])?>">
                            <i class="fa fa-comments"></i><?= $model->commentsCount?> Comments</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

views/site/category.php
<?php

use yii\widgets\ListView;

/** @var \yii\debug\models\timeline\DataProvider $categoryPosts */
/** @var string $categoryName */

$this->title = $categoryName;

?>
<h3>All posts by Category: <strong><?= $categoryName?></strong></h3>
<div class="row">
    <?= ListView::widget([
        'dataProvider' => $categoryPosts,
        'pager' => [
            'hideOnSinglePage' => true,
        ],
        'layout' => '{items} <div class="blog-pagination">{pager}</div>',
        'summary'=>'',
        'itemView' => '_short_post_view'
    ])?>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

    <?php endif; ?>

    <p>
        If you have business inquiries or other questions, please fill out the following form to contact us.
        Thank you.
    </p>

    <?php $form = ActiveForm::begin([
        'enableAjaxValidation' => true,
        'enableClientValidation' => false,
    ]); ?>

    <div class="row">
        <?= $form->field($model, 'name', ['options' => ['class' => 'col-xs-12 col-md-6']])
            ->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'phone', ['options' => ['class' => 'col-xs-12 col-md-6']])
            ->textInput([
                'class' => 'form-control',
                'id' => "phone",
                'type' => "tel",
                'value' => "+38(___)___-__-__",
                'pattern' => "^\+38(\s+)?\(?[0][0-9]{2}\)?(\s+)?[0-9]{3}-?[0-9]{2}-?[0-9]{2}$"
            ]) ?>
    </div>
    <div class="row">
        <?= $form->field($model, 'email', ['options' => ['class' => 'col-xs-12 col-md-6']]) ?>

        <?= $form->field($model, 'subject', ['options' => ['class' => 'col-xs-12 col-md-6']]) ?>
    </div>

    <?= $form->field($model, 'body', ['options' => ['class' => 'col-xs-12 row']])->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'reCaptcha')->widget(
        \himiklab\yii2\recaptcha\ReCaptcha::className(),
        ['siteKey' => Yii::$app->params['googleReCaptchaSiteKey']]
    ) ?>

    <div class="form-group col-xs-12 col-md-3 row">
        <?= Html::submitButton('Submit', ['class' => 'btn btn-submit', 'name' => 'contact-button']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\widgets\ListView;

$this->title = 'Blog';

/** @var \yii\debug\models\timeline\DataProvider $latestPosts */
?>

<div class="row">
    <?= ListView::widget([
        'dataProvider' => $latestPosts,
        'pager' => [
            'hideOnSinglePage' => true,
        ],
        'layout' => '{items} <div class="blog-pagination">{pager}</div>',
        'summary'=>'',
        'itemView' => '_short_post_view'
    ])?>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-8\">{input}</div>\n<div class=\"col-lg-3\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-8">
                <?= Html::submitButton('Login', ['class' => 'btn btn-submit', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>
</div>

views/site/page.php
<?php

/** @var \app\models\StaticPage $model */

use app\models\ContactForm;

$this->title = $model->name;
?>

<?= $model->content?>

<?php if ($model->is_form) :?>
    <?= $this->render('contact', ['model' => new ContactForm()]) ?>
<?php endif ?>

views/site/post.php
<?php

/** @var \app\models\Post $model */

use app\models\Post;
use yii\helpers\Html;
use yii\helpers\Url;

$this->title = $model->name;

?>

<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="single-blog blog-details two-column">
            <div class="post-thumb">
                <a href="#">
                    <!--                    <img src="images/blog/7.jpg" class="img-responsive" alt="">-->
                </a>
                <div class="post-overlay">
                    <span class="uppercase"><a href="#">14 <br><small>Feb</small></a></span>
                </div>
            </div>
            <div class="post-content overflow">
                <h2 class="post-title bold"><?= Html::a($model->name, [
                        'site/post',
                        'categoryUrl' => $model->category->url,
                        'postUrl' => $model->url
                    ])?></h2>
                <h3 class="post-author"><?= date('l jS \of F Y h:i:s A', $model->published_at) ?></h3>
                <p><?= $model->content ?></p>
                <div class="post-bottom overflow">
                    <ul class="nav navbar-nav post-nav">
                        <?php foreach ($model->publishedTags as $tag) : ?>
                            <li><?= Html::a('<i class="fa fa-tag"></i>' . $tag->name,
                                    ['site/tag', 'tagUrl' => $tag->url]) ?></li>
                        <?php endforeach ?>
                        <li><?= Html::a('<i class="fa fa-list-ul"></i>' . $model->category->name,
                                ['site/category-page', 'categoryOrPageUrl' => $model->category->url]) ?></li>
                        <li><a href="<?= Url::to([Post::getPostFullUrlByEntity($model->id)])?>">
                                <i class="fa fa-comments"></i><?= $model->commentsCount?> Comments</a></li>
                    </ul>
                </div>
                <div class="blog-share">
                    <span class='st_facebook_hcount'></span>
                    <span class='st_twitter_hcount'></span>
                    <span class='st_linkedin_hcount'></span>
                    <span class='st_pinterest_hcount'></span>
                    <span class='st_email_hcount'></span>
                </div>
                <?php echo \yii2mod\comments\widgets\Comment::widget([
                    'model' => $model,
                    'maxLevel' => 2,
                    'dataProviderConfig' => [
                        'pagination' => [
                            'pageSize' => 10
                        ],
                    ],
                    'listViewConfig' => [
                        'emptyText' => Yii::t('app', 'No comments found.'),
                    ],
                ]); ?>
            </div>
        </div>
    </div>
</div>



views/site/profile.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \webvimark\modules\UserManagement\models\forms\ChangeOwnPasswordForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Profile';
$this->params['breadcrumbs'][] = $this->title;
?>
<?php if ($message = Yii::$app->session->getFlash('success')) :?>
    <div class="subscribe-msg  vspacer15 bspacer15 text-success">
        <?= $message ?>
    </div>
<?php endif ?>
<div class="row">
    <div class="col-md-6">
        <section>
            <h2 class="section-title">Account info</h2>
            <div class="list-group">
                <a href="#" class="list-group-item">
                    <h3>Username</h3>
                    <p><?=Yii::$app->user->identity->username ?></p>
                </a>
                <?php if (!empty(Yii::$app->user->identity->registration_ip)) :?>
                    <a href="#" class="list-group-item">
                        <h3>Registration IP</h3>
                        <p><?=Yii::$app->user->identity->registration_ip ?></p>
                    </a>
                <?php endif?>
                <a href="#" class="list-group-item">
                    <h3>Created At</h3>
                    <p><?=date('jS M, y h:i A', Yii::$app->user->identity->created_at) ?></p>
                </a>
                <a href="#" class="list-group-item">
                    <h3>Updated At</h3>
                    <p><?=date('jS M, y h:i A', Yii::$app->user->identity->updated_at) ?></p>
                </a>
            </div> <!--list-group -->
        </section>
    </div>
    <div class="col-md-6">
        <section>
            <h3 class="section-title">Update your data</h3>
            <?php $form = ActiveForm::begin([
                'id'=>'user',
                'layout'=>'horizontal',
                'validateOnBlur'=>false,
            ]); ?>

            <?php if ( $model->scenario != 'restoreViaEmail' ): ?>
                <?= $form->field($model, 'current_password')->passwordInput(['maxlength' => 255, 'autocomplete'=>'off']) ?>

            <?php endif; ?>

            <?= $form->field($model, 'password')->passwordInput(['maxlength' => 255, 'autocomplete'=>'off']) ?>

            <?= $form->field($model, 'repeat_password')->passwordInput(['maxlength' => 255, 'autocomplete'=>'off']) ?>


            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <?= Html::submitButton(
                        '<span class="glyphicon glyphicon-ok"></span> Save',
                        ['class' => 'btn btn-submit']
                    ) ?>
                </div>
            </div>

            <?php ActiveForm::end(); ?>
        </section>
    </div>
</div>

views/site/tag.php
<?php

use yii\widgets\ListView;

/** @var \yii\debug\models\timeline\DataProvider $tagPosts */
/** @var string $tagName */

$this->title = $tagName;

?>
<h3>All posts by Tag: <strong><?= $tagName?></strong></h3>
<div class="row">
    <?= ListView::widget([
        'dataProvider' => $tagPosts,
        'pager' => [
            'hideOnSinglePage' => true,
        ],
        'layout' => '{items} <div class="blog-pagination">{pager}</div>',
        'summary'=>'',
        'itemView' => '_short_post_view'
    ])?>
</div>